### ISSUE TITLE
Search toggle button does not work on mobile when JS fails

### ISSUE THREAD

**Issue by 36degrees** [alphagov/static#838] opened 2016-10-04 15:40 UTC
Clicking the search button has no effect. Tested in Device mode in Google Chrome on Desktop.

![A picture's worth a thousand words…](https://cloud.githubusercontent.com/assets/121939/19080638/9794f878-8a4f-11e6-9ce0-d51550c245dd.gif)

Publishing Frontend Support: https://trello.com/b/gUJGoX6b/support-gov-uk-template-consolidation

**Comment by nickcolley** [comment] 2016-10-04 15:41
Can reproduce, thanks for raising @36degrees 👍 

Looks like we could have the button behave like a link unless JavaScript is available.

**Comment by fofr** [comment] 2017-03-07 13:58
Can we default to showing search?

**Comment by andysellick** [comment] 2022-01-31 16:10
Closing this issue as the header has been completely rebuilt as a new component.

**Closed by andysellick** 2022-01-31 16:10 UTC
Labels: publishing-frontend-support, bug
